#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries.

echo -e "---> \033[0;31m ACTION HOOK \033[0m:\033[46m \033[1;37mbuild \033[0m <---"
