#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo -e "---> \033[0;31m ACTION HOOK \033[0m:\033[46m \033[1;37mdeploy \033[0m <---"


echo -e '\033[0;32mactivating virtual environment . . . \033[0m'
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo -e '\033[0;32mapplying migrations \033[0m'
python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput

echo -e '\033[0;32mcollecting static files \033[0m'
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

echo -e "\033[0;31mstatus\033[0m: \033[42m\033[1;37m success \033[0m"

